title: The dynamic site is dead
description: SXSW 2014
hashtag: "static"
participants:
  - name: Danny Chapman
    twitter: dannychapman
    img: http://github.com/dannychapman.png
  - name: Ben Balter
    twitter: benbalter
    img: http://github.com/benbalter.png
  - name: Jessica Teal
    twitter: tealmedia
    img: "https://media.licdn.com/media/p/2/000/020/11e/28a9538.jpg"
  - name: Julie Herron
    twitter: slowdripcrazy
    img: "/images/herron.jpg"

exclude:
  - script
  - ".gitignore"
  - Gemfile
  - Gemfile.lock
  - readme.md
  - node_modules
  - ".sass-cache"
  - "package.json"
  - "*.scss"
  - "*.coffee"
  - "*.less"
  - src
pygments: true
markdown: kramdown
kramdown:
  parse_block_html: true
